version: '3'
services:
  fluentd:
    build: ./fluentd
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:5140:5140"

  elasticsearch:
    build: ./elasticsearch
      
  mongo:
    image: "mongo:3"

  graylog:
    build: ./graylog
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000