version: '3'
services:
  fluentd:
    build: ./fluentd
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:5140:5140"

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
  mongo:
    image: "mongo:3"

  graylog:
    image: graylog/graylog:4.2
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
      - mongo
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elastic:changeme@elasticsearch:9200
      GRAYLOG_IS_MASTER: true
      GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:9000/api/
      GRAYLOG_WEB_LISTEN_URI: http://0.0.0.0:9000/
      GRAYLOG_WEB_ENABLE_CORS: true
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
